---
name: AuthTools
version: 1.0.0_indev_#013
api: 1.8.0
depend:
- SimpleAuth
author: PEMapModder
main: authtools\AuthTools
description: A plugin that works around with SimpleAuth to add different featuers
website: https://github.com/PEMapModder/AuthTools
permission:
  authtools:
    description: AuthTools main permission node
    default: false
    children:
      authtools.directauth:
        description: Allow using DirectAuth (only for players)
        default: true
      authtools.changepw:
        description: Allow using /changepw (only for players)
        default: true
      authtools.chatpw:
        description: Allow speaking his own password in chat directly (only for players)
        default: false
...
